version: '2'

services:
    proxy:
        image: nginx:1.13
        container_name: proxy
        ports:
            - 17080:443
        volumes:
            - /home/alexey/task10_12_2/etc/nginx.conf:/etc/nginx/nginx.conf:ro
            - /home/alexey/task10_12_2/certs:/etc/nginx/certs:ro
            - /srv/log/nginx:/var/log/nginx
    web:
        image: httpd:2.4
        container_name: web
        ports:
            - 80:80
#networks:
#    test-network:
#        driver: bridge
