version: '2'

services:
    proxy:
        image: nginx:1.13
        container_name: proxy
        ports:
            - 17080:443
        volumes:
            - /srv/nginx-cfg/nginx.conf:/etc/nginx/nginx.conf:ro
            - /srv/certs:/etc/nginx/certs:ro
            - /srv/log/nginx:/var/log/nginx
